version: '3'
services:
  node:
    build:
      dockerfile: ./
      context: .
    volumes:
      - ./:/usr/src/app # ローカルとコンテナ内の同期
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true # https://teratail.com/questions/249875
